Invites = [
{'id': 'VH4nhwCM', 'group_name': 'Brautzeugin Hannah', 'people': [{'guest_name': 'Hannah'}, {'guest_name': 'Jannik'}]},
{'id': 'rGDSFCuM', 'group_name': 'Gruppe 0', 'people': [{'guest_name': 'Gast 0'}, {'guest_name': 'Gast 1'}, {'guest_name': 'Gast 2'}]},
{'id': 'TudWfm0v', 'group_name': 'Gruppe 1', 'people': [{'guest_name': 'Gast 0'}, {'guest_name': 'Gast 1'}, {'guest_name': 'Gast 2'}, {'guest_name': 'Gast 3'}, {'guest_name': 'Gast 4'}]},
{'id': 'IGi2VU2s', 'group_name': 'Gruppe 2', 'people': [{'guest_name': 'Gast 0'}, {'guest_name': 'Gast 1'}, {'guest_name': 'Gast 2'}, {'guest_name': 'Gast 3'}, {'guest_name': 'Gast 4'}]},
{'id': 'cNWoOFGt', 'group_name': 'Gruppe 3', 'people': [{'guest_name': 'Gast 0'}, {'guest_name': 'Gast 1'}, {'guest_name': 'Gast 2'}, {'guest_name': 'Gast 3'}, {'guest_name': 'Gast 4'}]},
{'id': 'ORGvR6E5', 'group_name': 'Gruppe 4', 'people': [{'guest_name': 'Gast 0'}, {'guest_name': 'Gast 1'}, {'guest_name': 'Gast 2'}]},
{'id': '7D4wdZIO', 'group_name': 'Gruppe 5', 'people': [{'guest_name': 'Gast 0'}, {'guest_name': 'Gast 1'}, {'guest_name': 'Gast 2'}, {'guest_name': 'Gast 3'}]},
{'id': 'tkdklfTd', 'group_name': 'Gruppe 6', 'people': [{'guest_name': 'Gast 0'}, {'guest_name': 'Gast 1'}]},
{'id': 'LFctNbI2', 'group_name': 'Gruppe 7', 'people': [{'guest_name': 'Gast 0'}, {'guest_name': 'Gast 1'}, {'guest_name': 'Gast 2'}]},
{'id': 'jpg3hm8i', 'group_name': 'Gruppe 8', 'people': [{'guest_name': 'Gast 0'}, {'guest_name': 'Gast 1'}, {'guest_name': 'Gast 2'}]},
{'id': 'xI5QRDc4', 'group_name': 'Gruppe 9', 'people': [{'guest_name': 'Gast 0'}, {'guest_name': 'Gast 1'}]},
{'id': 'yms6nIo1', 'group_name': 'Gruppe 10', 'people': [{'guest_name': 'Gast 0'}, {'guest_name': 'Gast 1'}, {'guest_name': 'Gast 2'}]},
{'id': 'aaDpSgCW', 'group_name': 'Gruppe 11', 'people': [{'guest_name': 'Gast 0'}, {'guest_name': 'Gast 1'}, {'guest_name': 'Gast 2'}]},
{'id': 'EJoq5DfQ', 'group_name': 'Gruppe 12', 'people': [{'guest_name': 'Gast 0'}, {'guest_name': 'Gast 1'}, {'guest_name': 'Gast 2'}]},
{'id': 'HcT7h3w2', 'group_name': 'Gruppe 13', 'people': [{'guest_name': 'Gast 0'}, {'guest_name': 'Gast 1'}, {'guest_name': 'Gast 2'}, {'guest_name': 'Gast 3'}, {'guest_name': 'Gast 4'}]},
{'id': 'pvojkfeG', 'group_name': 'Gruppe 14', 'people': [{'guest_name': 'Gast 0'}, {'guest_name': 'Gast 1'}, {'guest_name': 'Gast 2'}, {'guest_name': 'Gast 3'}, {'guest_name': 'Gast 4'}]},
{'id': '3lHwPkhp', 'group_name': 'Gruppe 15', 'people': [{'guest_name': 'Gast 0'}, {'guest_name': 'Gast 1'}, {'guest_name': 'Gast 2'}, {'guest_name': 'Gast 3'}]},
{'id': '2XO1arg4', 'group_name': 'Gruppe 16', 'people': [{'guest_name': 'Gast 0'}, {'guest_name': 'Gast 1'}, {'guest_name': 'Gast 2'}]},
{'id': 'KZ8jTkjR', 'group_name': 'Gruppe 17', 'people': [{'guest_name': 'Gast 0'}]},
{'id': 't0rJekj2', 'group_name': 'Gruppe 18', 'people': [{'guest_name': 'Gast 0'}, {'guest_name': 'Gast 1'}, {'guest_name': 'Gast 2'}, {'guest_name': 'Gast 3'}, {'guest_name': 'Gast 4'}]},
{'id': 'b3MLpkex', 'group_name': 'Gruppe 19', 'people': [{'guest_name': 'Gast 0'}, {'guest_name': 'Gast 1'}]},
{'id': 'NE0tT6pX', 'group_name': 'Gruppe 20', 'people': [{'guest_name': 'Gast 0'}, {'guest_name': 'Gast 1'}]},
{'id': 'K1ZzPXV2', 'group_name': 'Gruppe 21', 'people': [{'guest_name': 'Gast 0'}, {'guest_name': 'Gast 1'}]},
{'id': 'vXz7PFXC', 'group_name': 'Gruppe 22', 'people': [{'guest_name': 'Gast 0'}, {'guest_name': 'Gast 1'}]},
{'id': '9lXGT2c4', 'group_name': 'Gruppe 23', 'people': [{'guest_name': 'Gast 0'}, {'guest_name': 'Gast 1'}, {'guest_name': 'Gast 2'}, {'guest_name': 'Gast 3'}, {'guest_name': 'Gast 4'}]},
{'id': '96OOBjTn', 'group_name': 'Gruppe 24', 'people': [{'guest_name': 'Gast 0'}, {'guest_name': 'Gast 1'}, {'guest_name': 'Gast 2'}, {'guest_name': 'Gast 3'}]},
{'id': 'G0cu9uvw', 'group_name': 'Gruppe 25', 'people': [{'guest_name': 'Gast 0'}, {'guest_name': 'Gast 1'}]},
{'id': 'XcAIw8EL', 'group_name': 'Gruppe 26', 'people': [{'guest_name': 'Gast 0'}, {'guest_name': 'Gast 1'}]},
{'id': 'euIgjsa6', 'group_name': 'Gruppe 27', 'people': [{'guest_name': 'Gast 0'}, {'guest_name': 'Gast 1'}]},
{'id': '0H0Jwqim', 'group_name': 'Gruppe 28', 'people': [{'guest_name': 'Gast 0'}, {'guest_name': 'Gast 1'}, {'guest_name': 'Gast 2'}, {'guest_name': 'Gast 3'}, {'guest_name': 'Gast 4'}]},
{'id': 'jMiockG0', 'group_name': 'Gruppe 29', 'people': [{'guest_name': 'Gast 0'}]},
{'id': 'xJ7xaZuV', 'group_name': 'Gruppe 30', 'people': [{'guest_name': 'Gast 0'}, {'guest_name': 'Gast 1'}]},
{'id': '58yfAnfm', 'group_name': 'Gruppe 31', 'people': [{'guest_name': 'Gast 0'}, {'guest_name': 'Gast 1'}, {'guest_name': 'Gast 2'}]},
{'id': 'by4XIDBY', 'group_name': 'Gruppe 33', 'people': [{'guest_name': 'Gast 0'}, {'guest_name': 'Gast 1'}, {'guest_name': 'Gast 2'}, {'guest_name': 'Gast 3'}]},
{'id': 'iBwMqz9l', 'group_name': 'Gruppe 34', 'people': [{'guest_name': 'Gast 0'}, {'guest_name': 'Gast 1'}, {'guest_name': 'Gast 2'}, {'guest_name': 'Gast 3'}]},
{'id': 'EXYeAfRh', 'group_name': 'Gruppe 35', 'people': [{'guest_name': 'Gast 0'}, {'guest_name': 'Gast 1'}, {'guest_name': 'Gast 2'}, {'guest_name': 'Gast 3'}]},
{'id': 'KjnI8w9l', 'group_name': 'Gruppe 36', 'people': [{'guest_name': 'Gast 0'}]},
{'id': 'TyFYrnQd', 'group_name': 'Gruppe 37', 'people': [{'guest_name': 'Gast 0'}]},
{'id': 'kmEaGY7M', 'group_name': 'Gruppe 38', 'people': [{'guest_name': 'Gast 0'}, {'guest_name': 'Gast 1'}, {'guest_name': 'Gast 2'}, {'guest_name': 'Gast 3'}, {'guest_name': 'Gast 4'}]},
{'id': 'ZnBIhTbt', 'group_name': 'Gruppe 39', 'people': [{'guest_name': 'Gast 0'}]},
{'id': 'NINbiefo', 'group_name': 'Gruppe 40', 'people': [{'guest_name': 'Gast 0'}, {'guest_name': 'Gast 1'}]},
{'id': '4a5plUb1', 'group_name': 'Gruppe 41', 'people': [{'guest_name': 'Gast 0'}, {'guest_name': 'Gast 1'}, {'guest_name': 'Gast 2'}]},
{'id': '3GNJ567p', 'group_name': 'Gruppe 42', 'people': [{'guest_name': 'Gast 0'}, {'guest_name': 'Gast 1'}]},
{'id': 'Ef8lNAwK', 'group_name': 'Gruppe 43', 'people': [{'guest_name': 'Gast 0'}, {'guest_name': 'Gast 1'}]},
{'id': 'YiMODtKh', 'group_name': 'Gruppe 44', 'people': [{'guest_name': 'Gast 0'}, {'guest_name': 'Gast 1'}, {'guest_name': 'Gast 2'}, {'guest_name': 'Gast 3'}, {'guest_name': 'Gast 4'}]},
{'id': 'M4zpnE0w', 'group_name': 'Gruppe 45', 'people': [{'guest_name': 'Gast 0'}, {'guest_name': 'Gast 1'}]},
{'id': 'M7lg8kBt', 'group_name': 'Gruppe 46', 'people': [{'guest_name': 'Gast 0'}, {'guest_name': 'Gast 1'}, {'guest_name': 'Gast 2'}]},
{'id': 'w6SQR5lC', 'group_name': 'Gruppe 47', 'people': [{'guest_name': 'Gast 0'}]},
{'id': 'AcXbxQ9p', 'group_name': 'Gruppe 48', 'people': [{'guest_name': 'Gast 0'}, {'guest_name': 'Gast 1'}, {'guest_name': 'Gast 2'}]},
{'id': 'rRXgzYzq', 'group_name': 'Gruppe 49', 'people': [{'guest_name': 'Gast 0'}]},
{'id': 'Gb0uEV7G', 'group_name': 'Gruppe 50', 'people': [{'guest_name': 'Gast 0'}, {'guest_name': 'Gast 1'}, {'guest_name': 'Gast 2'}, {'guest_name': 'Gast 3'}]},
{'id': '9YOsbIlH', 'group_name': 'Gruppe 51', 'people': [{'guest_name': 'Gast 0'}, {'guest_name': 'Gast 1'}, {'guest_name': 'Gast 2'}, {'guest_name': 'Gast 3'}]},
{'id': 'eveOLLHK', 'group_name': 'Gruppe 52', 'people': [{'guest_name': 'Gast 0'}, {'guest_name': 'Gast 1'}, {'guest_name': 'Gast 2'}, {'guest_name': 'Gast 3'}]},
{'id': 'GCQOXpxc', 'group_name': 'Gruppe 53', 'people': [{'guest_name': 'Gast 0'}, {'guest_name': 'Gast 1'}]},
{'id': 'rCWGcYi7', 'group_name': 'Gruppe 54', 'people': [{'guest_name': 'Gast 0'}, {'guest_name': 'Gast 1'}, {'guest_name': 'Gast 2'}, {'guest_name': 'Gast 3'}, {'guest_name': 'Gast 4'}]},
{'id': 'SF627xdR', 'group_name': 'Gruppe 55', 'people': [{'guest_name': 'Gast 0'}, {'guest_name': 'Gast 1'}, {'guest_name': 'Gast 2'}, {'guest_name': 'Gast 3'}]},
{'id': 'VoH7JUsx', 'group_name': 'Gruppe 56', 'people': [{'guest_name': 'Gast 0'}, {'guest_name': 'Gast 1'}, {'guest_name': 'Gast 2'}, {'guest_name': 'Gast 3'}, {'guest_name': 'Gast 4'}]},
{'id': 'SBrzpN98', 'group_name': 'Gruppe 57', 'people': [{'guest_name': 'Gast 0'}, {'guest_name': 'Gast 1'}]},
{'id': 'GjNDh6mv', 'group_name': 'Gruppe 58', 'people': [{'guest_name': 'Gast 0'}, {'guest_name': 'Gast 1'}, {'guest_name': 'Gast 2'}]},
{'id': '2rxwU1bg', 'group_name': 'Gruppe 59', 'people': [{'guest_name': 'Gast 0'}, {'guest_name': 'Gast 1'}, {'guest_name': 'Gast 2'}, {'guest_name': 'Gast 3'}, {'guest_name': 'Gast 4'}]},
{'id': 'JaFciFlb', 'group_name': 'Gruppe 60', 'people': [{'guest_name': 'Gast 0'}]},
{'id': 'cNCq7qdz', 'group_name': 'Gruppe 61', 'people': [{'guest_name': 'Gast 0'}, {'guest_name': 'Gast 1'}, {'guest_name': 'Gast 2'}, {'guest_name': 'Gast 3'}]},
{'id': 'lF0Xtrql', 'group_name': 'Gruppe 62', 'people': [{'guest_name': 'Gast 0'}, {'guest_name': 'Gast 1'}, {'guest_name': 'Gast 2'}]},
{'id': 'MDTzVc6g', 'group_name': 'Gruppe 63', 'people': [{'guest_name': 'Gast 0'}, {'guest_name': 'Gast 1'}, {'guest_name': 'Gast 2'}]},
{'id': 'U6Q1AZGO', 'group_name': 'Gruppe 64', 'people': [{'guest_name': 'Gast 0'}, {'guest_name': 'Gast 1'}]},
{'id': 's7emaPdI', 'group_name': 'Gruppe 65', 'people': [{'guest_name': 'Gast 0'}, {'guest_name': 'Gast 1'}]},
{'id': 'j6nreADD', 'group_name': 'Gruppe 66', 'people': [{'guest_name': 'Gast 0'}, {'guest_name': 'Gast 1'}]},
{'id': 'CPBTT9cQ', 'group_name': 'Gruppe 67', 'people': [{'guest_name': 'Gast 0'}]},
{'id': 'L7wAVTIJ', 'group_name': 'Gruppe 68', 'people': [{'guest_name': 'Gast 0'}]},
{'id': 'Fz9eRH8Q', 'group_name': 'Gruppe 69', 'people': [{'guest_name': 'Gast 0'}, {'guest_name': 'Gast 1'}, {'guest_name': 'Gast 2'}]},
{'id': 'WGtT3Lsh', 'group_name': 'Gruppe 70', 'people': [{'guest_name': 'Gast 0'}, {'guest_name': 'Gast 1'}]},
{'id': 'MSQLStYR', 'group_name': 'Gruppe 71', 'people': [{'guest_name': 'Gast 0'}, {'guest_name': 'Gast 1'}, {'guest_name': 'Gast 2'}, {'guest_name': 'Gast 3'}, {'guest_name': 'Gast 4'}]},
{'id': 'CUfLbWud', 'group_name': 'Gruppe 72', 'people': [{'guest_name': 'Gast 0'}, {'guest_name': 'Gast 1'}, {'guest_name': 'Gast 2'}]},
{'id': 'Nq52Almv', 'group_name': 'Gruppe 73', 'people': [{'guest_name': 'Gast 0'}, {'guest_name': 'Gast 1'}, {'guest_name': 'Gast 2'}, {'guest_name': 'Gast 3'}, {'guest_name': 'Gast 4'}]},
{'id': 'L67LNHQ2', 'group_name': 'Gruppe 74', 'people': [{'guest_name': 'Gast 0'}, {'guest_name': 'Gast 1'}, {'guest_name': 'Gast 2'}, {'guest_name': 'Gast 3'}, {'guest_name': 'Gast 4'}]},
{'id': 'P1i452ZQ', 'group_name': 'Gruppe 75', 'people': [{'guest_name': 'Gast 0'}, {'guest_name': 'Gast 1'}, {'guest_name': 'Gast 2'}]},
{'id': 'w9Q5tOyo', 'group_name': 'Gruppe 76', 'people': [{'guest_name': 'Gast 0'}, {'guest_name': 'Gast 1'}, {'guest_name': 'Gast 2'}, {'guest_name': 'Gast 3'}]},
{'id': 'kOHTehhN', 'group_name': 'Gruppe 77', 'people': [{'guest_name': 'Gast 0'}, {'guest_name': 'Gast 1'}, {'guest_name': 'Gast 2'}]},
{'id': 'NWEyeLzG', 'group_name': 'Gruppe 78', 'people': [{'guest_name': 'Gast 0'}, {'guest_name': 'Gast 1'}, {'guest_name': 'Gast 2'}, {'guest_name': 'Gast 3'}]},
{'id': 'RJjxw5Qr', 'group_name': 'Gruppe 79', 'people': [{'guest_name': 'Gast 0'}, {'guest_name': 'Gast 1'}, {'guest_name': 'Gast 2'}]},
{'id': 'ocnpqs1o', 'group_name': 'Gruppe 80', 'people': [{'guest_name': 'Gast 0'}, {'guest_name': 'Gast 1'}]},
{'id': 'dyPRUQlA', 'group_name': 'Gruppe 81', 'people': [{'guest_name': 'Gast 0'}]},
{'id': '4oZ1FYOH', 'group_name': 'Gruppe 82', 'people': [{'guest_name': 'Gast 0'}, {'guest_name': 'Gast 1'}, {'guest_name': 'Gast 2'}, {'guest_name': 'Gast 3'}, {'guest_name': 'Gast 4'}]},
{'id': '6qVqDkK8', 'group_name': 'Gruppe 83', 'people': [{'guest_name': 'Gast 0'}, {'guest_name': 'Gast 1'}, {'guest_name': 'Gast 2'}, {'guest_name': 'Gast 3'}, {'guest_name': 'Gast 4'}]},
{'id': 'GoqfB8FU', 'group_name': 'Gruppe 84', 'people': [{'guest_name': 'Gast 0'}, {'guest_name': 'Gast 1'}]},
{'id': 'R9cT9lbH', 'group_name': 'Gruppe 85', 'people': [{'guest_name': 'Gast 0'}, {'guest_name': 'Gast 1'}, {'guest_name': 'Gast 2'}, {'guest_name': 'Gast 3'}, {'guest_name': 'Gast 4'}]},
{'id': 'SBn6tVLA', 'group_name': 'Gruppe 86', 'people': [{'guest_name': 'Gast 0'}, {'guest_name': 'Gast 1'}, {'guest_name': 'Gast 2'}]},
{'id': 'rxRGJre7', 'group_name': 'Gruppe 87', 'people': [{'guest_name': 'Gast 0'}, {'guest_name': 'Gast 1'}]},
{'id': 'ARuDsOzD', 'group_name': 'Gruppe 88', 'people': [{'guest_name': 'Gast 0'}, {'guest_name': 'Gast 1'}, {'guest_name': 'Gast 2'}, {'guest_name': 'Gast 3'}, {'guest_name': 'Gast 4'}]},
{'id': 'iDonWgOR', 'group_name': 'Gruppe 89', 'people': [{'guest_name': 'Gast 0'}, {'guest_name': 'Gast 1'}, {'guest_name': 'Gast 2'}, {'guest_name': 'Gast 3'}, {'guest_name': 'Gast 4'}]},
{'id': 'uyOu9Hqp', 'group_name': 'Gruppe 90', 'people': [{'guest_name': 'Gast 0'}, {'guest_name': 'Gast 1'}, {'guest_name': 'Gast 2'}, {'guest_name': 'Gast 3'}, {'guest_name': 'Gast 4'}]},
{'id': 'Uow0vtEn', 'group_name': 'Gruppe 91', 'people': [{'guest_name': 'Gast 0'}, {'guest_name': 'Gast 1'}]},
{'id': 'vI5CTplb', 'group_name': 'Gruppe 92', 'people': [{'guest_name': 'Gast 0'}]},
{'id': 'GNy14qDp', 'group_name': 'Gruppe 93', 'people': [{'guest_name': 'Gast 0'}, {'guest_name': 'Gast 1'}]},
{'id': 'HhVEhAu8', 'group_name': 'Gruppe 94', 'people': [{'guest_name': 'Gast 0'}]},
{'id': 'pxoHe8v7', 'group_name': 'Gruppe 95', 'people': [{'guest_name': 'Gast 0'}, {'guest_name': 'Gast 1'}]},
{'id': 'rB9x6TNU', 'group_name': 'Gruppe 96', 'people': [{'guest_name': 'Gast 0'}]},
{'id': 'EMYIPyGI', 'group_name': 'Gruppe 97', 'people': [{'guest_name': 'Gast 0'}, {'guest_name': 'Gast 1'}, {'guest_name': 'Gast 2'}, {'guest_name': 'Gast 3'}]},
{'id': 'ylGtmq5q', 'group_name': 'Gruppe 98', 'people': [{'guest_name': 'Gast 0'}, {'guest_name': 'Gast 1'}, {'guest_name': 'Gast 2'}]},
{'id': 'sn2zgpq5', 'group_name': 'Gruppe 99', 'people': [{'guest_name': 'Gast 0'}]},
{"id":"123","group_name":"Felix Eltern","people": [{"guest_name": "Connie"},{"guest_name": "Leo"}]},
{"id":"124","group_name":"Caro Eltern","people": [{"guest_name": "Heike"},{"guest_name": "Thomas"}]},
{"id":"125","group_name":"Familie Schlueter","people": [{"guest_name": "Christine"},{"guest_name": "Daniel"},{"guest_name": "Sophie"},{"guest_name": "Leo"}]},
{"id":"126","group_name":"Single Person A","people": [{"guest_name": "Single Person A"},{"guest_name": "Name des Anhangs :D"}]}
]